name = "nc4fortran"
description = "Lightweight object-oriented NetCDF4 interface"
categories = "io"
version = "1.6.1"

[build]
external-modules = ["netcdf"]
link = ["netcdf", "netcdff", "hdf5", "hdf5_hl", "hdf5_fortran", "hdf5hl_fortran"]
