set(netCDF_C_INCLUDE_DIRS ${CMAKE_INSTALL_FULL_INCLUDEDIR})

set(netcdf_c_cmake_args
-DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
-DCMAKE_PREFIX_PATH:PATH=${CMAKE_INSTALL_PREFIX}
-DCMAKE_BUILD_TYPE:STRING=Release
-DBUILD_SHARED_LIBS:BOOL=ON
-DNETCDF_ENABLE_PARALLEL4:BOOL=OFF
-DNETCDF_ENABLE_PNETCDF:BOOL=OFF
-DNETCDF_BUILD_UTILITIES:BOOL=OFF
-DNETCDF_ENABLE_TESTS:BOOL=off
-DBUILD_TESTING:BOOL=OFF
-DNETCDF_ENABLE_HDF4:BOOL=OFF
-DUSE_DAP:BOOL=off
-DNETCDF_ENABLE_DAP:BOOL=OFF
-DNETCDF_ENABLE_DAP2:BOOL=OFF
-DNETCDF_ENABLE_DAP4:BOOL=OFF
-DNETCDF_ENABLE_REMOTE_FUNCTIONALITY:BOOL=OFF
-DNETCDF_ENABLE_BYTERANGE:BOOL=OFF
-DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}
-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
-DZLIB_LIBRARY:FILEPATH=${ZLIB_LIBRARIES}
-DHDF5_ROOT:PATH=${HDF5_ROOT}
)
# BUILD_SHARED_LIBS=on for netcdf-fortran symbol finding bug

if(WIN32)
  set(netCDF_C_LIBRARIES ${CMAKE_INSTALL_FULL_BINDIR}/${CMAKE_SHARED_LIBRARY_PREFIX}netcdf${CMAKE_SHARED_LIBRARY_SUFFIX})
else()
  set(netCDF_C_LIBRARIES ${CMAKE_INSTALL_FULL_LIBDIR}/${CMAKE_SHARED_LIBRARY_PREFIX}netcdf${CMAKE_SHARED_LIBRARY_SUFFIX})
endif()

set(netCDF_C_INCLUDE_DIRS ${CMAKE_INSTALL_FULL_INCLUDEDIR})

string(JSON netcdfC_url GET ${json} netcdfC url)


ExternalProject_Add(NETCDF_C
URL ${netcdfC_url}
CONFIGURE_HANDLED_BY_BUILD TRUE
CMAKE_ARGS ${netcdf_c_cmake_args}
BUILD_BYPRODUCTS ${netCDF_C_LIBRARIES}
DEPENDS HDF5
USES_TERMINAL_DOWNLOAD true
USES_TERMINAL_UPDATE true
USES_TERMINAL_PATCH true
USES_TERMINAL_CONFIGURE true
USES_TERMINAL_BUILD true
USES_TERMINAL_INSTALL true
USES_TERMINAL_TEST true
)

# --- imported target

file(MAKE_DIRECTORY ${netCDF_C_INCLUDE_DIRS})
# avoid race condition

add_library(netCDF::netcdf INTERFACE IMPORTED)
target_include_directories(netCDF::netcdf INTERFACE "${netCDF_C_INCLUDE_DIRS}")
target_link_libraries(netCDF::netcdf INTERFACE "${netCDF_C_LIBRARIES}")

#set_property(TARGET netCDF::netcdf PROPERTY EXPORT_FIND_PACKAGE_NAME netCDF)

add_dependencies(netCDF::netcdf NETCDF_C)
