name: ci

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci.yml"
  release:
    types: [published]


jobs:

  linux:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    env:
      CTEST_SITE: GitHub_Ubuntu

    steps:
    - uses: actions/checkout@v2

    - name: install hdf5
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build gfortran libnetcdff-dev

    - name: CDash
      run: ctest -S ci.cmake -V

    - name: Install package
      run: |
        cmake -B build -DCMAKE_INSTALL_PREFIX:PATH=~/nc4fortran
        cmake --install build

    - name: configure examples
      run: cmake -S Examples -B Examples/build -Dnc4fortran_ROOT:PATH=~/nc4fortran
    - name: build examples
      run: cmake --build Examples/build --parallel
    - name: Test examples
      run: ctest --parallel 2 --output-on-failure
      working-directory: Examples/build

    - name: create package
      if: github.event.action == 'published'
      run: cpack --config build/CPackConfig.cmake

    - name: Upload artifact
      if: github.event.action == 'published'
      uses: actions/upload-artifact@v1
      with:
        name: binary-archive
        path: build/package

    - name: get version
      if: github.event.action == 'published'
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/package/nc4fortran-${{ steps.get_version.outputs.VERSION }}-Linux.tar.gz
        asset_name:  nc4fortran-${{ steps.get_version.outputs.VERSION }}-Linux.tar.gz
        asset_content_type: application/zip


  linuxCmake313:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2

    - name: install netcdf4
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libnetcdff-dev

    - name: get CMake 3.13
      run: |
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.13.5/cmake-3.13.5-Linux-x86_64.tar.gz
        tar xf cmake-3.13.5-Linux-x86_64.tar.gz
        echo "${GITHUB_WORKSPACE}/cmake-3.13.5-Linux-x86_64/bin" >> $GITHUB_PATH

    - run: cmake -B build
    - run: cmake --build build --parallel
    - run: ctest --parallel 2 --output-on-failure
      working-directory: build


  mac:
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      CC: gcc-10
      FC: gfortran-10
      CTEST_SITE: GitHub_MacOS

    steps:
    - uses: actions/checkout@v2

    - run: brew install netcdf ninja

    - name: CDash
      run: ctest -S ci.cmake -V

    - name: Install package
      run: |
        cmake -B build -DCMAKE_INSTALL_PREFIX:PATH=~/nc4fortran
        cmake --install build

    - run: cmake -S Examples -B Examples/build -Dnc4fortran_ROOT:PATH=~/h5fortran
    - run: cmake --build Examples/build --parallel
    - run: ctest --parallel 2 --output-on-failure
      working-directory: Examples/build

    - name: create package
      if: github.event.action == 'published'
      run: cpack --config build/CPackConfig.cmake

    - name: Upload artifact
      if: github.event.action == 'published'
      uses: actions/upload-artifact@v1
      with:
        name: binary-archive
        path: build/package

    - name: get version
      if: github.event.action == 'published'
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Upload release asset
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/nc4fortran-${{ steps.get_version.outputs.VERSION }}-Darwin.tar.gz
        asset_name:  nc4fortran-${{ steps.get_version.outputs.VERSION }}-Darwin.tar.gz
        asset_content_type: application/zip
