name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CMAKE_INSTALL_PREFIX: ~/libs
  CMAKE_PREFIX_PATH: ~/libs
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci.yml"
      - "!scripts/**"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  base:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    env:
      FC: gfortran-14

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:

    - &checkout
      uses: actions/checkout@v6

    - &ncdf-linux
      name: install NetCDF (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libnetcdff-dev

    - &ncdf-macos
      name: install NetCDF (macOS)
      if: runner.os == 'macOS'
      run: brew install netcdf-fortran

    - run: cmake --workflow reldebug

    - run: cmake --install build

    - &example
      name: Example workflow
      working-directory: example
      run: cmake --workflow default

  shared:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    env:
      FC: gfortran-14

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:

    - *checkout

    - *ncdf-linux

    - *ncdf-macos

    - run: cmake --workflow shared

    - run: cmake --install build-shared

    - *example


  build:
    needs: base

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    env:
      CC: gcc-14
      FC: gfortran-14

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - *checkout

    - name: install HDF5 (macOS)
      if: runner.os == 'macOS'
      run: brew install hdf5

    - name: install HDF5 (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libhdf5-dev

    - run: cmake --workflow default

    - run: cmake --install build

    - *example


  linux-coverage:
    if: false
    needs: base
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - *checkout
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: install prereqs
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libnetcdff-dev

    - name: install Gcovr
      run: pip install gcovr

    - run: cmake --workflow coverage

    - uses: actions/upload-artifact@v7
      with:
        name: coverage-report-html
        path: build-coverage/coverage/
