name: ci

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CTEST_PARALLEL_LEVEL: 3
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2

    - name: install libs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build gfortran libnetcdff-dev

    - run: cmake --preset multi --install-prefix ~

    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

    - run: cmake --install build

    - name: configure examples
      run: cmake -S Examples -B Examples/build -Dnc4fortran_ROOT=~
    - name: build examples
      run: cmake --build Examples/build --parallel
    - name: Test examples
      run: ctest --test-dir Examples/build --output-on-failure


  mac:
    needs: linux
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - run: brew install netcdf ninja

    - run: cmake --preset multi --install-prefix ~

    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

    - run: cmake --install build

    - run: cmake -S Examples -B Examples/build -Dnc4fortran_ROOT=~
    - run: cmake --build Examples/build --parallel
    - run: ctest --test-dir Examples/build --output-on-failure
