name: ci

env:
  CTEST_PARALLEL_LEVEL: 4
  CMAKE_BUILD_TYPE: Release
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci.yml"

jobs:

  base:
    runs-on: ${{ matrix.img.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        shared: [true, false]
        img: [
          {os: ubuntu-latest, fc: gfortran, cmd: sudo apt update && sudo apt install --no-install-recommends ninja-build libnetcdff-dev},
          {os: macos-latest, fc: gfortran-11, cmd: brew install netcdf ninja }
        ]

    env:
      FC: ${{ matrix.img.fc }}

    steps:
    - uses: actions/checkout@v2

    - name: install system libs
      run: ${{ matrix.img.cmd }}

    - run: cmake --preset multi -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

    - run: cmake --install build

    - name: configure examples
      run: cmake -S Examples -B Examples/build -DCMAKE_PREFIX_PATH=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - name: build examples
      run: cmake --build Examples/build
    - name: Test examples
      run: ctest --test-dir Examples/build -V


  linux-build:
    needs: base
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2

    - name: install libs
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libhdf5-dev

    - run: cmake -B build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}
    - run: cmake --build build --parallel
    - run: ctest --test-dir build --preset default
    - run: cmake --install build

    - name: configure examples
      run: cmake -S Examples -B Examples/build -DCMAKE_PREFIX_PATH=${{ runner.temp }}
    - name: build examples
      run: cmake --build Examples/build --parallel
    - name: Test examples
      run: ctest --test-dir Examples/build -V


  linux-coverage:
    if: github.event_name == 'release'
    needs: base
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: install prereqs
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libnetcdff-dev

    - name: install Gcovr
      run: pip install gcovr

    - run: cmake --preset coverage
    - run: cmake --build --preset coverage --parallel

    - name: Code coverage
      run: cmake --build --preset run-coverage

    - uses: actions/upload-artifact@v2
      with:
        name: coverage-report-html
        path: build-coverage/coverage/



  mac-build:
    if: github.event_name == 'release'
    needs: base
    runs-on: macos-latest
    timeout-minutes: 30
    env:
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - name: install libs
      run: brew install hdf5

    - run: cmake -B build --install-prefix=${{ runner.temp }}
    - run: cmake --build build
    - run: ctest --test-dir build --preset default
    - run: cmake --install build

    - name: configure examples
      run: cmake -S Examples -B Examples/build -Dnc4fortran_ROOT=${{ runner.temp }}
    - name: build examples
      run: cmake --build Examples/build --parallel
    - name: Test examples
      run: ctest --test-dir Examples/build -V
