name: ci

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CTEST_SITE: GitHub_Ubuntu
      CTEST_PARALLEL_LEVEL: 2

    steps:
    - uses: actions/checkout@v2

    - name: install libs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build gfortran libnetcdff-dev

    - run: cmake --preset default -DCMAKE_INSTALL_PREFIX=~
    - run: cmake --build --preset default
    - run: ctest --preset default
    - run: cmake --install build

    - name: configure examples
      run: cmake -S Examples -B Examples/build -Dnc4fortran_ROOT=~
    - name: build examples
      run: cmake --build Examples/build --parallel
    - name: Test examples
      run: ctest --test-dir Examples/build --output-on-failure


  linux-gcc7:
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    env:
      CTEST_PARALLEL_LEVEL: 2

    steps:
    - uses: actions/checkout@v2

    - name: install libs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libnetcdff-dev

    - run: cmake --preset make
    - run: cmake --build --preset default
    - run: ctest --preset default


  linuxCmake314:
    needs: linux
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CTEST_PARALLEL_LEVEL: 2

    steps:
    - uses: actions/checkout@v2

    - name: install netcdf4
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libnetcdff-dev

    - name: get CMake 3.14
      run: |
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.14.7/cmake-3.14.7-Linux-x86_64.tar.gz
        tar xf cmake-3.14.7-Linux-x86_64.tar.gz
        echo "${GITHUB_WORKSPACE}/cmake-3.14.7-Linux-x86_64/bin" >> $GITHUB_PATH

    - run: cmake -B build
    - run: cmake --build build --parallel
    - run: ctest --output-on-failure
      working-directory: build


  mac:
    needs: linux
    runs-on: macos-latest
    timeout-minutes: 20
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      CC: gcc-11
      FC: gfortran-11
      CTEST_PARALLEL_LEVEL: 3

    steps:
    - uses: actions/checkout@v2

    - run: brew install netcdf ninja

    - run: cmake --preset default -DCMAKE_INSTALL_PREFIX=~
    - run: cmake --build --preset default
    - run: ctest --preset default
    - run: cmake --install build

    - run: cmake -S Examples -B Examples/build -Dnc4fortran_ROOT=~
    - run: cmake --build Examples/build --parallel
    - run: ctest --test-dir Examples/build --output-on-failure
