name: ci
env:
   HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libnetcdff-dev

    - run: cmake -B build
    - run: cmake --build build --parallel

    - run: ctest --parallel 2 --output-on-failure
      working-directory: build

    - name: build examples
      run: |
        cmake -B Examples/build -S Examples
        cmake --build Examples/build

    - name: test examples
      run: ctest -V
      working-directory: Examples/build


  mac:
    needs: linux
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install gcc netcdf ninja

    - run: cmake -B build
    - run: cmake --build build --parallel

    - run: ctest --parallel 2 --output-on-failure
      working-directory: build
