name: ci_cmake

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
  pull_request:
    paths:
      - "**.f90"
      - "**.F90"

jobs:

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: brew install gcc netcdf pkg-config
    - run: cmake -B build
      env:
        FC: gfortran-9
        CC: gcc-9
        CXX: g++-9
    - run: cmake --build build --parallel
    - run: cmake --build build --target test
