name: ci_fpm

on:
  push:
    paths:
      - "fpm.toml"
      - ".github/workflows/ci_fpm.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      FPM_FFLAGS: -I/usr/include/ -I/usr/include/hdf5/serial
      FPM_LDFLAGS: -L/usr/lib/x86_64-linux-gnu/ -L/usr/lib/x86_64-linux-gnu/hdf5/serial

    steps:

    - uses: fortran-lang/setup-fpm@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: install NetCDF4
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libnetcdff-dev

    - uses: actions/checkout@v3

    - run: fpm build
    - run: fpm test
