name: ci_mac

on:
  push:
    paths:
      - "**.build"
      - "**.txt"
      - "**.f90"
      - ".github/workflows/ci_mac.yml"
  pull_request:
    paths:
      - "**.build"
      - "**.txt"
      - "**.f90"
      - ".github/workflows/ci_mac.yml"

jobs:

  meson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: brew install gcc ninja netcdf pkg-config
    - run: pip install meson
    - run: meson setup build
      env:
        FC: gfortran-9
        CC: gcc-9
    - run: ninja -C build

 # this catches configuration and build log
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Meson_Buildlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build -v

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - run: brew install gcc netcdf pkg-config

    - run: cmake -B build
      env:
        FC: gfortran-9
        CC: gcc-9
        CXX: g++-9
    - run: cmake --build build --parallel

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_CMake_Buildlog
        path: build/CMakeFiles/CMakeError.log

    - run: ctest --parallel
      working-directory: build

    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_CMake_Testlog
        path: build/Testing/Temporary/LastTest.log
