name: ci_windows
env:
  CMAKE_GENERATOR: Ninja
  CTEST_PARALLEL_LEVEL: 4
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_windows.yml"
  pull_request:
  release:
    types: [published]


jobs:

  msys2:
    timeout-minutes: 30
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-hdf5
    # cmake install needed because of default to msys2 shell

    - uses: actions/checkout@v2

    - run: cmake --preset multi --install-prefix=${HOME}
    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

    - run: cmake --install build

# NetCDF-C packaging issue with HDF5--ignores CMAKE_MODULE_PATH and uses broken factory FindHDF5
# and can't seem to override
    # - name: configure examples
    #   run: cmake -S Examples -B Examples/build -Dnc4fortran_ROOT=${HOME}
    # - name: build Examples
    #   run: cmake --build Examples/build
    # - name: Test Examples
    #   run: ctest --test-dir Examples/build -V
