name: ci_windows

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_windows.yml"
      - "!cmake/netcdf.cmake"
      - "!cmake/netcdf-c.cmake"
      - "!cmake/hdf5.cmake"
      - "!scripts/**"


jobs:

  msys2:
    timeout-minutes: 30
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-hdf5
          mingw-w64-x86_64-netcdf

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v3

    - name: Configure NetCDF4
      run: >-
        cmake
        -G Ninja
        -S scripts
        -B scripts/build
        -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}

    - name: Build/install NetCDF4
      run: cmake --build scripts/build --parallel

    - name: configure nc4fortran
      run: >-
        cmake
        -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
        --preset multi
        --install-prefix ${{ runner.temp }}
        -DCMAKE_PREFIX_PATH=${{ runner.temp }}

    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

    - run: cmake --install build

# NetCDF-C packaging issue with HDF5--ignores CMAKE_MODULE_PATH and uses broken factory FindHDF5
# and can't seem to override
    # - name: configure examples
    #   run: cmake -S example -B example/build -DCMAKE_PREFIX_PATH=${{ runner.temp }}
    # - name: build Examples
    #   run: cmake --build example/build
    # - name: Test Examples
    #   run: ctest --test-dir example/build -V
